# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e05ead6e216b9e9e7b4d94592ccc0ced6eb51736fce1f9832ca7f39138d31c85a0ec2052d1c835b95d55f70697020a932d34bd02d3154a9bf67afcfec734dca

test:
  secret_key_base: b4c8126e28eab41ff1c768fca8b4dec23e22cba55d6ecf5b02207da44cb6ffcb59a1227df86e2bfa0121c750091bedb9a82249bc6755cd95a6d76c2e6337414b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
